### ISSUE TITLE
Why HTraversable_/HSequence instead of HFoldable/HTraversable ?

### ISSUE THREAD

**Issue by alexfmpe** [well-typed/generics-sop#101]
This hinders discoverability a bit. It also seems that while the docs for the methods themselves refer the ones they generalize, there's no such association being made between the classes. Is that related to the less standard names?

**Comment by phadej** [comment]
The naming is for historical reasons. See e.g. `HSequence` class in `generics-sop-0.2.0.0`: http://hackage.haskell.org/package/generics-sop-0.2.0.0/docs/Generics-SOP-Classes.html#t:HSequence Changing the name could broke someone (though one could argue that `HSequence` constraint isn't explicitly written in user code).

I remember thinking about the name of `HTraversable_`, but seems there are no discussion on the PR https://github.com/well-typed/generics-sop/pull/59

At least we are consistently using the other name :)

**Comment by kosmikus** [comment]
I don't think any effort is being made to duplicate the base class hierarchy. The classes in generics-sop are all just there to provide a more uniform interface for `NP`, `NS`, `POP`, and `SOP`. They're not currently intended to be open or reusable beyond that point.

It might be worthwhile trying to do that, but I think it'd be a quite significant change to the library, and I'd then probably also consider flipping the arguments of all these constructors.

**Comment by kosmikus** [comment]
Going to close this for now. Feel free to reopen if you think this should have higher priority.
