### ISSUE TITLE
Does not compile on GHC 6.8.3 Windows x86_64

### ISSUE THREAD

**Issue by ndmitchell** [well-typed/generics-sop#104]
Neither 0.4.0.1 nor 0.3.2.0 compile on Windows in less than an hour (they were still running at 100% CPU when I killed them)

**Comment by phadej** [comment]
8.6.3? Duplicate of https://github.com/well-typed/generics-sop/issues/93

**Comment by ndmitchell** [comment]
Yes, thanks! 8.6.4 is a disaster of a release (missing half the files on Windows), so I'll try going backwards.

**Comment by phadej** [comment]
@ndmitchell Could you try https://www.haskell.org/ghc/blog/201904080-ghc-8.6.5-rc1-released.html, I'm sure Ben would like Windows-specific feedback,

**Comment by phadej** [comment]
@ndmitchell I understand, no worries.

**Comment by hsenag** [comment]
FWIW I'm using 8.6.5 x86_64 on Windows fine with generics-sop.
