### ISSUE TITLE
Why are metadata types not implemented in terms of `K`?

### ISSUE THREAD

**Issue by AriFordsham** [well-typed/generics-sop#136]
Is there any reason `StrictnessInfo` and `FieldInfo` are not implemented in terms of `K`?

e.g.

```haskell
data StrictnessInfo' = StrictnessInfo SourceUnpackedness SourceStrictness DecidedStrictness
type StrictnessInfo  = K StrictnessInfo'

type FieldInfo = K FieldName
```

(You couldn't do this with `ConstructorInfo` because it's a GADT).

**Comment by kosmikus** [comment]
It's just that the dedicated types are more meaningfully named (at the cost of potentially missing useful instances). It's a difficult trade-off, perhaps, but I don't currently feel motivated to make a breaking change here.
