### ISSUE TITLE
`Generics.SOP.Code` doesn't expand when applied to a newtype with a `GHC.Generics.Generic` instance

### ISSUE THREAD

**Issue by blamario** [well-typed/generics-sop#152]
More weirdly, `Generics.SOP.GGP.GCode` does expand, even though the former is just a synonym of the latter.
I'm not sure if this is a GHC bug or something specific to `generics-sop`, but I'm reporting it here first.
```
GHCi, version 8.10.7: https://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /tmp/haskell-stack-ghci/2a3bbd58/ghci-script
Prelude> :module + Generics.SOP Generics.SOP.GGP
Prelude Generics.SOP Generics.SOP.GGP> :set -XDeriveGeneric
Prelude Generics.SOP Generics.SOP.GGP> newtype N = N Int deriving GHC.Generics.Generic
Prelude Generics.SOP Generics.SOP.GGP> :k! Code N
Code N :: [[*]]
= Code N
Prelude Generics.SOP Generics.SOP.GGP> :k! GCode N
GCode N :: [[*]]
= '[ '[Int]]
```

**Comment by phadej** [comment]
You don't derive `Generics.SOP.Generic`.

**Comment by blamario** [comment]
I missed that `Code` is an associated type under the `SOP.Generic` class. But in that case, why don't I get an compiler error? I'd expect
```
No instance for (Generic N) arising from a use of ‘Code’
```

**Comment by kosmikus** [comment]
@blamario I'm sorry, I don't think this qualifies as a bug in generics-sop. Associated types are available for use outside of the class. There is, afaik, currently no tracking between the use of an associated type and the class it is defined in. The only functional change by moving a type family into a class is that you cannot define instances for it without defining an instance for the class. I don't think this has ever been different in GHC. If you're unhappy with this, I think you should probably bring it up as a GHC issue instead.

**Comment by blamario** [comment]
Nothing to be sorry about @kosmikus. I reported a GHC issue at https://gitlab.haskell.org/ghc/ghc/-/issues/21098
