### ISSUE TITLE
Help using `hcoerce` when `xs` isn't available

### ISSUE THREAD

**Issue by evanrelf** [well-typed/generics-sop#168]
Hi there! Hopefully a question about how to use `sop-core` is acceptable here. GitHub discussions seem to be disabled for this repo. Feel free to close if not.

I've written a working `FromJSON` instance for `NS I xs`:

```haskell
instance All FromJSON xs => FromJSON (NS I xs) where
  parseJSON v =
      unK
    $ traverse__NP (mapKK sequence_NS)
    $ apInjs'_NP
    $ cpure_NP (Proxy @FromJSON)
    $ parseJSON v
```

Now I want to generalize this to work on any `NS f xs` (assuming I can coerce from the previous more concrete instance). But I'm struggling to use `hcoerce`/`fromI_NS`, because it involves a type variable that isn't in scope. I basically want something that looks sorta like this:

```haskell
instance (forall ws. AllZip (LiftedCoercible I f) ws xs, All FromJSON xs) => FromJSON (NS f xs) where
  parseJSON v =
      fmap (fromI_NS @_ @ws)
    $ unK
    $ traverse__NP (mapKK sequence_NS)
    $ apInjs'_NP
    $ cpure_NP (Proxy @FromJSON)
    $ parseJSON v
```

This won't actually work of course, since the `ws` isn't in scope for `fromI_NS`, but hopefully that illustrates the issue.

There's this intermediate `ws` thing that isn't specified anywhere, and its ambiguity messes everything up. `ws` in my code snippets is equivalent to `xs` in the signature for `fromI_NS`:

```haskell
fromI_NS :: forall f xs ys. AllZip (LiftedCoercible I f) xs ys => NS I xs -> NS f ys
```

I know that `ws` and `xs` are related (in pseudocode, `ws == fmap f xs`), but I'm not sure how to express that, or if it would resolve the type errors.

**Comment by evanrelf** [comment]
I think I made some progress towards reducing the problem using `:.:`/`Comp`:

```haskell
instance All FromJSON xs => FromJSON (NS f xs) where
  parseJSON v =
      unK
    $ traverse__NP (mapKK sequence'_NS)
    $ apInjs'_NP
    $ cpure_NP (Proxy @FromJSON) $ Comp $ parseJSON v
```

But I'm still getting a similar error:

```
    • Could not deduce (FromJSON (f a))
        arising from a use of ‘parseJSON’
      from the context: All FromJSON xs
        bound by the instance declaration
        at src/Main.hs:215:10-46
      or from: FromJSON a
        bound by a type expected by the context:
                   forall a. FromJSON a => (:.:) Parser f a
        at src/Main.hs:220:36-53
    • In the second argument of ‘($)’, namely ‘parseJSON v’
      In the second argument of ‘($)’, namely ‘Comp $ parseJSON v’
      In the second argument of ‘($)’, namely
        ‘cpure_NP (Proxy @FromJSON) $ Comp $ parseJSON v’
    |
220 |     $ cpure_NP (Proxy @FromJSON) $ Comp $ parseJSON v
    |                                           ^^^^^^^^^
```

**Comment by phadej** [comment]
```diff
 -All FromJSON xs
+All (Compose FromJSON f) xs
 ```
 
See e.g. https://hackage.haskell.org/package/sop-core-0.5.0.2/docs/src/Data.SOP.NP.html#line-141

**Comment by evanrelf** [comment]
Aha, thank you! I read this part of the `Compose` docs:

> Composition of constraints.

...and thought it wasn't applicable because my `f` wasn't a constraint. But I overlooked this part:

> The kind of `g`, however, is `l` -> `k` and can thus be a normal type constructor.

Thank you! 🙂

My working implementation:

```haskell
instance FromJSON a => FromJSON (I a) where
  parseJSON v = I <$> parseJSON v

instance All (Compose FromJSON f) xs => FromJSON (NS f xs) where
  parseJSON v =
      unK
    $ traverse__NP (mapKK sequence'_NS)
    $ apInjs'_NP
    $ cpure_NP (Proxy @(Compose FromJSON f))
    $ Comp
    $ parseJSON v
```
