### ISSUE TITLE
Should we add hapInjs'_POP

### ISSUE THREAD

**Issue by phadej** [well-typed/generics-sop#28]
The `NP` variant is simply `hap injections`, but `POP` variant is:

```haskell
hapInjs'_POP :: SListI xss => POP f xss -> NP (K (SOP f xss)) xss
hapInjs'_POP = hmap (kfirst SOP) . hap injections . unPOP
```

which is quite lenghty. Or, is there a shorter way to say that?

**Comment by kosmikus** [comment]
So this is just `apInjs_POP` without the final call to `hcollapse`?

**Comment by phadej** [comment]
yes, except that `apInjs_POP = map SOP . apInjs_NP . unPOP`, i.e. it loses the structure in `apInjs_NP` already.

**Comment by kosmikus** [comment]
I assume you have a use case for this which doesn't involve collapsing the result?

**Comment by phadej** [comment]
It occurs when I need to `hczipWith` a constructor info (i.e. `NP SOP.ConstructorInfo (SOP.Code a)`).

**Comment by kosmikus** [comment]
It's actually a bit strange that the standard variants of `apInjs` apply `hcollapse`. So yes, I'm in favour of this  as well. At least adding the two functions to `Generics.SOP.NP`. But they should be called `apInjs'_NP` and `apInjs'_POP`, without the `h` which is currently only used for the overloaded variants.

I'm also not opposed to adding a `HApInjs` class that offers the two functions in overloaded form.

I'd appreciate a PR, but if you don't get around to it, I might try to do it myself.

**Comment by phadej** [comment]
I'll make a PR with `apInjs'_POP` and `apInjs'_NP`; let's see if I'll get `HApInjs` to work too.
