### ISSUE TITLE
version 0.1.0.3 doesn't compile

### ISSUE THREAD

**Issue by peti** [well-typed/generics-sop#3]
A complete build log is at http://hydra.cryp.to/build/286232/log/raw. The significant bit seems to be:

```
Building generics-sop-0.1.0.3...
Preprocessing library generics-sop-0.1.0.3...

src/Generics/SOP.hs:299:0:
     error: missing binary operator before token "("
     #if !(defined(__HADDOCK_VERSION__)) || MIN_TOOL_VERSION_haddock(2,14,0)
     ^
```

Maybe the `cpp` extension isn't declared in the cabal file?

**Comment by peti** [comment]
@kosmikus, the problem is that not bumping the package is actually work than bumping it. Updates can be applied automatically by tools, but deciding not to update is something a human being has to do. IMHO, there are no golden rules here. I'll update packages, and I may or may not notice that the update breaks something. If I do, I'll probably revert the update, but I don't notice, then someone else has to help out. This has gotten even more important now that Nixpkgs distributes basically all of Hackage. There's no way a single person can keep that package set consistent. I guess what I'm trying to say is that I get the impression you'd like me to be responsible for keeping `generics-sop` building even in the presence of a new version that breaks the build. I don't want that responsibility, really. I'll do as much as I can, but there are limits to what I can do.

**Comment by kosmikus** [comment]
@peti You know that I know that it's a lot of work supporting packages, and I appreciate all the work you're doing in nixpkgs. I also know that it's not (in general) possible to do things manually for such a large package set as Hackage. I was merely suggesting that it could be a refinement of an automatic policy to retain a known building older version in favour of (or in addition to) a new release that breaks for whatever reason. It's perfectly fine for you to dismiss this idea as "not feasible for now".

**Comment by peti** [comment]
I think it's good policy. It's just hard to implement with the tools we have, I'm afraid.
