### ISSUE TITLE
Make a release with type-level metadata

### ISSUE THREAD

**Issue by kosmikus** [well-typed/generics-sop#30]
Probably based on the type-level-metadata-simpler branch.

Advantages:

- This would finally solve #8, which is open for a very long time.
- This would allow the release of kosmikus/records-sop which has been requested in kosmikus/records-sop#1.
- The unreleased work I'm doing on datatype-generic migrations using generics-sop is also depending on these features.
- The changes should be mostly backwards compatible.
- I'd welcome more feedback on the interface, and more experience with the type-level features (see below).

Disadvantages:

- I'm not completely happy with the new features yet, so they'll most likely change again in the future.
- There is no easy way to add this without dropping ghc-7 support.

Any thoughts? @phadej @nmattia @jkarni ?

**Comment by phadej** [comment]
@kosmikus can you make a PR from your branch, it would be easier to review and comment

**Comment by kosmikus** [comment]
@phadej Sure. Although it's not documented very well.

**Comment by kosmikus** [comment]
Done. #31.

**Comment by kosmikus** [comment]
PR is merged. I'll try to do the release within the next few days unless anyone objects.

**Comment by kosmikus** [comment]
Released 0.3.0.0 today.
