### ISSUE TITLE
Create a benchmark suite

### ISSUE THREAD

**Issue by kosmikus** [well-typed/generics-sop#40]
I currently have two branches I'm experimenting with that are in some sense performance-oriented: static-case and compact-representation.

Before merging any of these, I'd like to measure relative performance, so it'd be good to have a number of performance tests that'd allow to test how various generics-sop functions perform. It'd also be good to measure the overhead of generics-sop itself, by comparing it to generic-deriving / built-in GHC generics, and to hand-written code.

I may end up doing this ultimately, but I don't have a lot of time. So if anyone wants to help with this, it'd be much appreciated.

**Comment by kosmikus** [comment]
I might try to start on this during ZuriHac.

**Comment by kosmikus** [comment]
I think @andorp is now working on this.

**Comment by andorp** [comment]
Yes, thanks for the reminder to be more formal. :)
