### ISSUE TITLE
Add special code aliases

### ISSUE THREAD

**Issue by phadej** [well-typed/generics-sop#44]
```haskell
type IsRecordType a xs = (Generic a, Code a ~ '[ xs ])
type IsEnumType a = (Generic a, All ((~) '[]) (Code a))
type IsWrappedType a x = (Generic a, Code a ~ '[ '[ x ] ])
```

I have `IsRecordType` (inlined) and `IsWrappedType` (with different name) used in our code. And now as I think about it, I'll should use `IsEnumType` too as I have quite a few enumerations with very very similar boilerplate just copypasted around.

So :+1: to all of these.

---

About naming, record implies it has field names; which isn't always true. Would `IsProductType` be ~correct and not clash with `records-sop`?

**Comment by phadej** [comment]
- `IsWrappedType` would cover the need for `UnSingleton`. 

- `NewtypeRep` - something I come very quickly with, somehow tried to make it reasonable if read infix; didn't succeed well though.

- `IsNewtype a x = (Coercible a x, IsWrappedType a x)` ?

- *(inlined)* means that I didn't define the type-alias, but wrote the LHS directly (it's not that much longer!)

- I often mix "record" and "product" too, because many have a concept of record from other languages. But IMHO `IsProductType` would fit the current `generics-sop` vocabulary much better (and want clash with records-sop).

**Comment by kosmikus** [comment]
@phadej I'm ok with `IsProductType`. Let's go for that.

And I agree that these aliases don't save a lot of characters. But I think they're more descriptive, in particular to people who don't know much about generics-sop and just want to get an understanding of what the function does from looking at the type signature.

Using `Coercible` for `IsNewtype` looks like a neat trick. I would have defined something like (untested)
```
type family IsNewtypeInfo (i :: DatatypeInfo) :: Constraint where
  IsNewtypeInfo (Newtype _ _ _) = ()

type IsNewtype a x = (IsWrappedType a x, HasDatatypeInfo a, IsNewtypeInfo (DatatypeInfoOf a))
```

But this introduces a `HasDatatypeInfo` constraint and relies on type-level metadata. Whereas `Coercible` does not. So I think I like your suggestion better.

**Comment by kosmikus** [comment]
I've opened PR #46 for this.

**Comment by kosmikus** [comment]
Done via PR #46.
