### ISSUE TITLE
Make `Generic` a superclass of `HasDatatypeInfo`

### ISSUE THREAD

**Issue by kosmikus** [well-typed/generics-sop#45]
Is there any good reason not to do this? I'm a bit surprised we did not do this from the beginning.

The type signature of `datatypeInfo` mentions `Code`, and `Code` is associated with `Generic`, so it cannot possibly be defined for a type without a `Generic` instance. It thus seems as if there is no way to ever have a `HasDatatypeInfo` instance without a `Generic` instance.

@edsko Do you have an opinion here?

**Comment by edsko** [comment]
I guess morally they are independent, which is why they've been defined to be independent. 'HasDatatypeInfo' seems a bit odd as a function constraint to say 'we must have a generic representation of this thing'; but of course in practice one is very unlikely to occur without the other. No strong opinion either way.

**Comment by phadej** [comment]
In similar-ish cases I had the `type` family defined in separate class, e.g.

```haskell
class HasCode a where
   type Code a :: [[*]]

class HasCode a => Generic a where
    to :: ...
    from :: ...

class HasCode a => HasDatatypeIno a where
    datatypeInfo :: ... 
```

But in this case there is no *real* reason to do so, so I'd be ok with `HasDatatypeInfo` having `Generic` as a superclass. As a bonus I don't have many examples where you need *only* `HasDatatypeInfo`, usually you need `Generic` as well, so the signatures will be shorter.

**Comment by kosmikus** [comment]
@edsko My point is that it's not just unlikely, it's currently impossible afaics. You cannot give a valid definition of `HasDatatypeInfo` without having an instance for `Generic`. As @phadej says, it would become possible if we moved `Code` out of the class. Not sure if there are any use cases for that.

**Comment by edsko** [comment]
`Code` could be a completely independent type family surely? Anyway, like I said, I don't feel very strongly about it :)

**Comment by phadej** [comment]
`binary-tagged` uses only `datatypeInfo` to generate "structure hash"; but it's very niche use-case.

**Comment by kosmikus** [comment]
@phadej Yes, certainly I don't argue that functions can make use of only the datatype info. But if that doesn't increase the number of datatypes it works on, I don't see why it matters.

@edsko Yes, `Code` could be moved out of the class. But are there scenarios where you can give a `Code` for a type, but no conversion functions?

**Comment by phadej** [comment]
@kosmikus Maybe there are situations where you don't want to give conversion functions, but have no problem with `datatypeInfo` (a bit like `Typeable` and `Data`). Or you'd be ok only with `from`, but not `to` (IIRC that was discussed in the past), because other direction may violate the invariant.

**Comment by kosmikus** [comment]
@phadej Yes, maybe there are. But I'm trying to find concrete examples if possible. Would abstract types count? But I think we cannot currently define `datatypeInfo` for built-in types either, because we don't have a concept of constructors ...

**Comment by kosmikus** [comment]
I'm still inclined to make this change, but I won't do it for 0.3.1.0. It's somewhat unclear anyway whether this would require a major version bump. In practice, I doubt it would (or even could?) break a single program. But technically, the PVP doesn't allow superclass changes without major bumps, I think.

**Comment by phadej** [comment]
We should do this for `0.4.0.0`

**Comment by kosmikus** [comment]
Yes, you're right. Sorry for the milestone change. That was unintended.
