### ISSUE TITLE
Exhaustivity workaround in ap_NS

### ISSUE THREAD

**Issue by phadej** [well-typed/generics-sop#57]
I was surprised to see, which compiles even on GHC-8.0 and GHC-8.2 without warnings

```haskell
ap_NS :: NP (f -.-> g) xs -> NS f xs -> NS g xs
ap_NS (Fn f  :* _)   (Z x)   = Z (f x)
ap_NS (_     :* fs)  (S xs)  = S (ap_NS fs xs)
ap_NS _ _ = error "inaccessible"
```

Is this "bug" recorded in GHC Trac?

**Comment by kosmikus** [comment]
No, at least not by me. I never read the work on the new exhaustiveness checker carefully enough to understand whether this is a bug. I do think it's not claiming to be complete.

The given function is one which is difficult for Agda/Idris/etc as well, and would require an explicit "impossible" case.

A workaround that is ok with current GHC is to flip the arguments around and write this instead:
```
ap_NS :: NP (f -.-> g) xs -> NS f xs -> NS g xs
ap_NS = flip flip_ap_NS

flip_ap_NS :: NS f xs -> NP (f -.-> g) xs -> NS g xs
flip_ap_NS (Z x ) (Fn f :* _ ) = Z (f x)
flip_ap_NS (S xs) (_    :* fs) = S (ap_NS fs xs)
```

I'm not sure if it's worth making this change just to avoid the `error` call though.

**Comment by RyanGlScott** [comment]
This isn't a GHC bug at all—`ap_NS` is truly non-exhaustive. If you don't believe me, try running `ap_NS Nil undefined` in GHCi :)

@kosmikus recommends one way to avoid coverage checking warnings in https://github.com/well-typed/generics-sop/issues/57#issuecomment-326324473. Another perfectly cromulent way to silence warnings is to write a third case to the original `ap_NS` definition, like so:

```haskell
{-# LANGUAGE EmptyCase #-}

ap_NS :: NP (f -.-> g) xs -> NS f xs -> NS g xs
ap_NS (Fn f  :* _)   (Z x)   = Z (f x)
ap_NS (_     :* fs)  (S xs)  = S (ap_NS fs xs)
ap_NS Nil            x       = case x of {}
```

**Comment by kosmikus** [comment]
@RyanGlScott Yes, you're right. Thanks for the explanation. I'm going to close this issue then, because the original question is answered, regardless of what we end up doing in the code.
