### ISSUE TITLE
Relax TH upper bound of  0.2.5.0 on Hackage (as a Hackage revision)

### ISSUE THREAD

**Issue by Mikolaj** [well-typed/generics-sop#95]
Could you bump TH dependency of generics-sop-0.2.5.0 on Hackage from `<2.13`  to `<2.14`? I tested that it compiles fine. Thank you! Alternatively, I will gladly do that myself, given Hackage credentials.

The story: I'm using postgresql-simple-sop (maintainer currently not responsive), which depends on generics-sop-0.2.5.0 and to compile it under GHC 8.4.4 I'd need the TH dependency of generics-sop-0.2.5.0 to be relaxed. This is a stop-gap measure, but will do fine while I keep nagging the postgresql-simple-sop maintainer.

**Comment by phadej** [comment]
http://hackage.haskell.org/package/generics-sop-0.2.5.0/revisions/
