### ISSUE TITLE
GHC loop when reporting error

### ISSUE THREAD

**Issue by hsenag** [well-typed/generics-sop#99]
The following (cut down) code causes GHC 8.6.3 to start reporting an error and then loop:

```
{-# LANGUAGE TypeApplications, ScopedTypeVariables, GADTs, MultiParamTypeClasses,
                         FlexibleContexts, AllowAmbiguousTypes #-}
module Main where

import Data.Functor.Identity
import Generics.SOP

class (f a ~ b) => IsHKD f a b

dump
  :: forall t1
   . (Generic t1, AllZip2 (IsHKD Identity) (Code t1) (Code t1))
  => t1 -> ()
dump = dump_SOP @(Code t1) . from

dump_SOP
  :: forall xss f
   . (AllZip2 (IsHKD f) xss xss)
  => SOP I xss
  -> ()
dump_SOP _ = ()

main = return ()
```

```
GHCi, version 8.6.3: http://www.haskell.org/ghc/  :? for help
[1 of 1] Compiling Main             ( src/Main.hs, interpreted )

src/Main.hs:13:8: error:
```

It's legitimate that there is an error - at the very least I haven't given the compiler enough information to instantiate `f` to `Identity` - but having the compiler loop instead of telling me the error is inconvenient :-)

I inlined generics-sop and cut it down further.

```
{-# LANGUAGE FlexibleContexts, FlexibleInstances, AllowAmbiguousTypes,
                         UndecidableSuperClasses #-}
module M where

data I = I

class All x => All x

class AllZip2 f
instance AllZip2 f

f1 :: (All x, AllZip2 I) => x -> ()
f1 = f2

f2 :: AllZip2 f => x -> ()
f2 _ = ()
```
The key features of the `generics-sop` code that trigger it seem to be the recursive instance for `All` (in the `generics-sop` codebase this is actually `All Top => All c`) and the catch-all instance for `AllZip2`.

I guess that even though `generics-sop` is using `UndecidableSuperClasses`, GHC ought not to be looping indefinitely in the middle of trying to report an error. I'll report a bug there after the trac->gitlab migration is done.  But I thought it would be useful to at least have a record of it here.

**Comment by hsenag** [comment]
Now also reported to GHC : https://gitlab.haskell.org/ghc/ghc/issues/16414

**Comment by kosmikus** [comment]
Interestingly, ghc-8.4 seems to "correctly" report an error for your first example, but it also loops for the second.

The way I see this right now, it's an unfortunate GHC bug that affects only incorrect programs, so I'll probably not take action. Or do you have "correct" programs that make the checker loop?

**Comment by hsenag** [comment]
I'm not aware of it happening for correct programs, though it's quite painful to actually write a correct program under these circumstances :-) I don't think there's much you could do anyway, and SPJ has already got a fix ready in GHC, so doing nothing seems fine to me. I thought it'd be useful to have the issue recorded here in any case as someone else might run across it.

**Comment by kosmikus** [comment]
Yes, it's definitely useful to have it recorded here.
